$script_ansible = <<-SCRIPT
  apt update && \
  apt install -y software-properties-common && \
  apt-add-repository --yes --update ppa:ansible/ansible && \
  apt install -y ansible
SCRIPT

$script_clone_repo = <<-SCRIPT
  git clone https://github.com/pratadaniel94/website
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.name = "host_ansible"
    end

    config.vm.network "public_network", ip: "192.168.1.25"
    config.vm.provision "shell", inline: $script_ansible
    config.vm.provision "shell",
        inline: "cp /vagrant/configs/id_rsa /home/vagrant && chmod 600 /home/vagrant/id_rsa && chown vagrant:vagrant /home/vagrant/id_rsa"
end