Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.define "web" do |web|
    web.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.name = "web_server"
    end
        web.vm.network "public_network", ip: "192.168.1.27"
        web.vm.provision "shell",
            inline: "cat /vagrant/id_rsa.pub >> .ssh/authorized_keys"
    end

    config.vm.define "db" do |db|
    db.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.name = "mysql_server"
    end
        db.vm.network "public_network", ip: "192.168.1.26"
        db.vm.provision "shell",
            inline: "cat /vagrant/id_rsa.pub >> .ssh/authorized_keys"
    end
end